### ISSUE TITLE
Allow usage in html files (for svelte.js)

### ISSUE THREAD

**Issue by docmars** [Microsoft/vscode-references-view#29]
When highlighting Javascript references in the `<script>` tag in my single-file Svelte components (.html), **List All References** option isn't available, nor are any of the extension's other functions.

Is there a preference I can set to support other file types / languages? Maybe it'd be more appropriate to support `svelte` as a language?

Thanks!

**Comment by jrieken** [comment]
This extension only shows references, it doesn't compute them. That means to get support for a certain language you must find (or write) and extension that does so.
