### ISSUE TITLE
Close "Reference Search" when no editor is open

### ISSUE THREAD

**Issue by ludwig801** [Microsoft/vscode-references-view#33]
Tested with PHP classes, JS variables and JS classes, but suspected to be a general issue with "References Search" tab.

1. Open a file with a desired variable/class to inspect
2. Right-click -> "List All References" (or press Shift + Alt + F12)
3. Close all open editor files
4. On the left pane, in the "Reference Search" tab, click on "Clear Reference Results".
5. It is expected that the tab would be cleared and closed, but it remains open (when an editor file is open, this issue does not happen).

**Comment by jrieken** [comment]
this #25
