### ISSUE TITLE
Clearing results flickers

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-references-view#36]
When you clear the results you briefly see both empty view message and tree of results:

![before](https://user-images.githubusercontent.com/900690/49280043-6232e680-f489-11e8-9165-b82843729e8e.gif)

**Comment by jrieken** [comment]
@sandy081 I fire the change on event on the provider (which then async calls back into me) and at the same time I update the message. Can you maybe sync both event or should I delay(?) showing the message?

**Comment by sandy081** [comment]
There is some asynchronosity for the tree to get updated after the change event is triggered. If you are setting the message immediately after triggering the change event, mostly message appears first and then tree is updated. I think what is missing here is a callback for tree refresh and you have to workaround this by delaying updating message until you update the tree (like after getChildren is called).

**Comment by jrieken** [comment]
> like after getChildren is called

Yeah, that's what I now have but it's not nice and others that implement an empty/default message might run into the same issue. Maybe add an `emptyMessage` in addition to `message`?

**Comment by sandy081** [comment]
How about adding a `refresh` method to the tree view that returns a promise?

**Comment by jrieken** [comment]
Hm, a `refresh` method is somewhat against the event a provider should offer... I can image that extension writer start using that instead of triggering events... Maybe a `onDidUpdate`-event (on the view) which signals that it has processed the last event from the provider.

**Comment by sandy081** [comment]
May be. Did the change you did fixed the issue?

**Comment by jrieken** [comment]
Yeah, it is much better now

**Comment by sandy081** [comment]
Cool. I would like to wait until it is reported further by other users before introducing any API.

**Comment by jrieken** [comment]
yeah, lets see what happens ;-)
