### ISSUE TITLE
Add messages when panel is empty

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-references-view#5]
**Feature request**
Two cases:

* Add a message to the empty result panel when no references are returned
* Add a message to the empty that explains how to use the extension when you have just started VS Code or have cleared the results

Depends on https://github.com/Microsoft/vscode/issues/61312

**Comment by jrieken** [comment]
this is related to https://github.com/Microsoft/vscode-references-view/issues/12 and https://github.com/Microsoft/vscode-references-view/issues/11
